# Generated by Django 4.2.13 on 2024-05-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KinoFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoActers',
            fields=[
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('acter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.acters')),
            ],
        ),
        migrations.AddField(
            model_name='acters',
            name='films',
            field=models.ManyToManyField(to='main.kinofilms'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('info_acter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.infoacters')),
            ],
        ),
    ]
