# Generated by Django 4.2.13 on 2024-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_infoacters_info_acter_infoacters_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acters',
            name='films',
        ),
        migrations.AddField(
            model_name='kinofilms',
            name='films',
            field=models.ManyToManyField(to='main.acters'),
        ),
    ]
