# Generated by Django 4.2.13 on 2024-05-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_acters_films_kinofilms_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinofilms',
            name='films',
        ),
        migrations.AddField(
            model_name='kinofilms',
            name='actors',
            field=models.ManyToManyField(to='main.acters'),
        ),
    ]
