# Generated by Django 4.2.13 on 2024-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_kinofilms_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinofilms',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='main.acters'),
        ),
    ]
